### ISSUE TITLE
Not really an issue...

### ISSUE THREAD

**Issue by anhquan0412** [laconicllama/google-locations#1]
Just want to say thank you. I got to see what you did with this dataset in a meetup and was inspired to do my own data analysis (https://github.com/anhquan0412/google-location)

**Comment by laconicllama** [comment]
Thanks for sending me the link to your code! I thought your Exploratory Data Analysis was really interesting, and the plots and Folium visualizations really helped with understanding the data. I should have added similar visualizations to my own notebook!

I will definitely be using your code as reference when I do more in-depth analyses of my own data. Thanks again!
